Repository bavix/gripmock, pull requests merged in 2025-05, with the labels that each got.

#601 bump deps
  go.mod
  go.sum
  pkg/yaml2json/engine.go
Labels: go

#602 fix: service name without leading dot
  internal/app/grpc_server.go
Labels: bug

#603 add examples/projects/circle-convertor
  examples/projects/circle-converter/service.proto
  examples/projects/circle-converter/stub.yaml
  examples/projects/circle-converter/test.gctf
Labels: units

#606 [3.2] fix case input.{contains,equals,matches} object empty
  examples/projects/echo/case_v1_empty.gctf
  examples/projects/echo/stubs_v1.yml
  go.mod
  go.sum
Labels: bug, deeply, v3

#607 bump gripmock-ui
  go.mod
  go.sum
Labels: dependencies

#608 [3.2] Add delay support
  .github/workflows/golangci-lint.yml
  Makefile
  go.mod
  go.sum
  internal/app/grpc_server.go
Labels: enhancement, v3
